### ISSUE TITLE
运行的时候存在报错

### ISSUE THREAD

**Issue by littleheary** [D001UM3/CTF-RSA-tool#3]
python solve.py  -e 17 -p 473398607161 -q 4511491 --private

返回的结果是
Traceback (most recent call last):
  File "solve.py", line 148, in <module>
    attackobj.attack()
  File "/soft/ctf/ctf-rsatools/lib/RSAutils.py", line 126, in attack
    factors = factor_N.solve(self.n, self.e, self.c, self.sageworks)
  File "/soft/ctf/ctf-rsatools/lib/factor_N.py", line 18, in solve
    return pastctfprimes(N) or noveltyprimes(N) or wiener_attack(N, e) or factordb(N) or comfact_cn(N, c) or smallq(N) or p_q_2_close(N) or None
  File "/soft/ctf/ctf-rsatools/lib/factor_N.py", line 97, in pastctfprimes
    if N % prime == 0:
TypeError: unsupported operand type(s) for %: 'NoneType' and 'long'
TypeError: unsupported operand type(s) for %: 'NoneType' and 'long'

**Comment by 6u661e** [comment]
python solve.py -e 17 -N 2135733555619387051 --private

p和q参数供分解不出n的时候用
