### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by Everest0516** [D001UM3/CTF-RSA-tool#5]
root@kali:~/tools/CTF-RSA-tool# python solve.py --verbose -k examples/jarvis_oj_hardRSA/pubkey.pem --decrypt examples/jarvis_oj_hardRSA/flag.enc
Traceback (most recent call last):
  File "solve.py", line 148, in <module>
    attackobj = lib.RSAutils.RSAAttack(args)
  File "/root/tools/CTF-RSA-tool/lib/RSAutils.py", line 34, in __init__
    self.c = libnum.s2n(f.read().strip())
  File "/usr/local/lib/python2.7/dist-packages/libnum/strings.py", line 10, in s2n
    return int(s.encode("utf-8").hex(), 16)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 1: ordinal not in range(128)

**Comment by Everest0516** [comment]
请问是什么问题，kali虚拟机中运行的，谢谢

**Comment by happyfmy** [comment]
F:\honker\tools\CTF-RSA-tool-master>python2 solve.py -v -k pubkey.pem --decrypt flag.enc
Traceback (most recent call last):
  File "solve.py", line 148, in <module>
    attackobj = lib.RSAutils.RSAAttack(args)
  File "F:\honker\tools\CTF-RSA-tool-master\lib\RSAutils.py", line 34, in __init__
    self.c = libnum.s2n(f.read().strip())
  File "D:\Program Files\Python27\lib\site-packages\libnum\strings.py", line 10, in s2n
    return int(s.encode().hex(), 16)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 2: ordinal not in range(128)

**Comment by happyfmy** [comment]
和楼上一样的问题

**Comment by CLMonster** [comment]
Traceback (most recent call last):
  File "solve.py", line 148, in <module>
    attackobj = lib.RSAutils.RSAAttack(args)
  File "/Users/wang/hackingfiles/CTF-RSA-tool/lib/RSAutils.py", line 34, in __init__
    self.c = libnum.s2n(f.read().strip())
  File "/Library/Python/2.7/site-packages/libnum/strings.py", line 10, in s2n
    return int(s.encode("utf-8").hex(), 16)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 2: ordinal not in range(128)


同问，使用mac下的python2.7也遇到了同样的问题

**Comment by adfnekc** [comment]
我也遇到了同样的问题。。

**Comment by Nixiabing** [comment]
mac和kali上遇到同样的问题
